# Generated by Django 5.1.6 on 2025-04-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='data_of_brith',
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_brith',
            field=models.DateField(blank=True, null=True),
        ),
    ]
