# Generated by Django 5.1.6 on 2025-02-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_feed', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.CharField(max_length=250),
        ),
    ]
