# Generated by Django 5.1.6 on 2025-04-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_feed', '0010_news_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='view_count',
            field=models.IntegerField(default=1),
        ),
    ]
